---
- name: install and activate plugin(s)
  command: ./bin/console sw:plugin:install {{ item }} --activate
  args:
    chdir: "{{ shopware_install_path }}"
  with_items: "{{ plugins }}"
  register: command_result
  failed_when: "'PHP Fatal error' in command_result.stderr or 'was not found' in command_result.stdout or 'Unable to install' in command_result.stderr"
  changed_when: "'{{ item }} is already installed' not in command_result.stdout"
