---
- include: refresh-plugins.yml

- include: download-plugins.yml
  vars:
    plugins:
      - SwagLicense

- include: refresh-plugins.yml

- include: install-and-activate-plugins.yml
  vars:
    plugins:
      - SwagLicense

- name: install licenses | copy license files
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/"
  with_items: "{{ shopware_licenses }}"

- name: install licenses | import licenses
  command: ./bin/console swaglicense:import /tmp/{{ item }}
  args:
    chdir: "{{ shopware_install_path }}"
  with_items: "{{ shopware_licenses }}"
  register: command_result
  failed_when: "'PHP Fatal error' in command_result.stderr"
  changed_when: "'Updated/Inserted' in command_result.stdout_lines[1] and not ' 0 ' in command_result.stdout_lines[1]"
