---
- name: install remote plugins | merge lists of remote plugins and demo data plugin
  set_fact:
    remote_plugins: "{{ shopware_remote_plugins + shopware_remote_plugins_demo_data }}"
  when: shopware_install_demo_data

- name: install remote plugins | set list of remote plugins without demo data
  set_fact:
    remote_plugins: "{{ shopware_remote_plugins }}"
  when: not shopware_install_demo_data

- include: download-plugins.yml
  vars:
    plugins: "{{ remote_plugins }}"

- include: refresh-plugins.yml

- name: install remote plugins | clear cache
  command: ./var/cache/clear_cache.sh
  args:
    chdir: "{{ shopware_install_path }}"
  failed_when: "'PHP Fatal error' in command_result.stderr"
  changed_when: false

- include: install-and-activate-plugins.yml
  vars:
    plugins: "{{ remote_plugins }}"
